onCreate:
    - sudo apt-get update -y
    - sudo apt install python3-dev python3-virtualenv build-essential ruby ruby-dev gem redis-server memcached redis-tools virtualenv apt-transport-https ca-certificates curl software-properties-common -y
    - |
          echo "############################# POSTGRES INSTALLATION #######################################"
          # sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          # wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          # sudo apt-get update
          sudo apt install postgresql postgresql-contrib
          sudo -u postgres psql postgres -c "ALTER USER postgres PASSWORD 'root'"
          sudo -u postgres psql postgres -c "CREATE DATABASE peeljobs WITH OWNER = postgres"
    - |
        echo "############################# NODE INSTALLATION #######################################"
        curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
        sudo apt-get install -y nodejs
        sudo apt-get install node-less
        sudo gem install sass
        sudo ln -s /usr/bin/lessc /usr/local/bin/lessc
    - |
        echo "############################# DOCKER INSTALLATION #######################################"
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
        sudo apt install docker-ce -y
        docker run -d --name elasticsearch -p 127.0.0.1:9200:9200 -p 127.0.0.1:9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.17.6
    - |
          echo "############################# DJANGO INSTALLATION #######################################"
          virtualenv -p python3 ../venv
          . ../venv/bin/activate
          cp ENV.md .env
          pip install -U pip
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py update_index
          python manage.py loaddata cities 

  onStart:
    - |
          . ../venv/bin/activate
          WS_DOMAIN=`cat /home/ubuntu/runcode/ws-url-domain.txt`
          printf "\nGO TO THIS URL TO VIEW PAGE \033[4;34m https://8000-${WS_DOMAIN}\033[0;30m\n\n"
          docker run -d --name elasticsearch -p 127.0.0.1:9200:9200 -p 127.0.0.1:9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.17.6
          python manage.py runserver